print( "Please enter the following information ")

first = input("First name: ")
last = input("Last name: ")
email = input("Email: ")
phone = input("Phone number: ")
job_title = input("Job Title: ")
id_number = input("ID Number: ")
hair = input("Hair color: ")
eye = input("Eye color: ")
training = input("Training:")
month = input("Month: ")

print("The ID card is: ")

print("-------------------------------------------")

print(f"{last.upper()}, {first.title()}")
print(job_title.title())
print(f"ID: {id_number}")
print()
print(f"{email.lower()}")
print(f"{phone}")
print()
print(f"Hair: {hair.capitalize()}      Eyes: {eye.capitalize()}")
print(f"Month: {month.capitalize()}      Training: {training.capitalize()}")
print("-------------------------------------------")